[project]
name = "phishly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black==23.12.1",
    "flake8==6.1.0",
    "pytest==7.4.3",
    "python-dotenv==1.0.0",
]
